### ISSUE TITLE
Upvotes

### ISSUE THREAD

**Issue by ishan0102** [ishan0102/engblogs#24]
Add upvote mechanism that uses IP address based users

**Comment by raghunandanbhat** [comment]
IP based upvoting may not be that robust.
- Multiple people upvoting from a shared network and only one upvote gets registered from the shared network.
- One person upvoting from different IPs (VPN, proxy, etc).

Device fingerprinting could be another option, but privacy is a concern.

**Comment by ishan0102** [comment]
Yeah makes sense but the only alternative is user accounts I think. Don't think upvotes need to be very robust, not intending them to be very accurate, just want it to be easy to use.
