### ISSUE TITLE
Font swapped characters

### ISSUE THREAD

**Issue by pahyde** [ishan0102/engblogs#28]
Cool project!

I was using the search function and noticed that the backslash and forward slash characters are swapped.

On inspection, it turns out the berkeley.woff file has 2 pairs of swapped characters
1. '/' and '\'
2. '#' and '*'

I'm guessing this is not intended

**Comment by ishan0102** [comment]
Sweet thanks for the PR, will take a look at this later! Think you're probably right about this, good catch
