### ISSUE TITLE
Filter button

### ISSUE THREAD

**Issue by raghunandanbhat** [ishan0102/engblogs#3]
@ishan0102 are you planning to add a search and filter feature?
If you're not working on it already, I will start and will make a PR soon

Features: 
- [x] Filter
- [ ] Search

**Comment by ishan0102** [comment]
Was planning on adding something but haven't started working on it, so feel free to make a PR!

**Comment by ishan0102** [comment]
You may need to create a mock data file btw, lmk if you need anything else. Thanks for working on this!

**Comment by raghunandanbhat** [comment]
I just implemented **Search** and I was wondering which column I should search in `posts` table. As of now, I'm searching the `description` column of the `posts` table.

Also, do we need to store search and filter results in sessionStorage or query the database every time?

**Comment by ishan0102** [comment]
For search I was thinking of searching the description and title columns. And I think it's a good idea to query the db everytime, I was just playing around with it and hit sessionStorage capacity when filtering with many combinations. I'm going to merge the branch pretty soon, I made a lot of structural changes so you may need to merge into your branch. I'm going to move each piece into a separate component so if you want to make a separate file for the search functionality that would be great.

**Comment by raghunandanbhat** [comment]
> I think it's a good idea to query the db everytime, I was just playing around with it and hit sessionStorage capacity when filtering with many combinations. 

Yes. I tried multiple ways- query the db vs filter out results in sessionStorage vs store the combination of filters in sessionStorage. 
If you're hitting the sessionStorage capacity, it is better to query every time.

> I'm going to move each piece into a separate component so if you want to make a separate file for the search functionality that would be great.

Sure. Once I have all structural changes, I will finish search and make a new PR
