### ISSUE TITLE
Improvement Scopes

### ISSUE THREAD

**Issue by Neilblaze** [ishan0102/engblogs#8]
@ishan0102 The interface has a minimalistic design, and I have reviewed several other enhancement suggestions that appear reasonable. Here are a few suggestions from my end:

1. Implement a **bookmark** or **save-for-later** option.
2. Include a **public upvote** feature.
3. Update or redefine the **UI layout**.
4. Add **dark mode** (IMP)
5. Expand the feed sources by including more blog links.
6. Consider implementing [embeddings](https://github.com/ishan0102/engblogs/issues/7) (already listed)
7. [Display tech stack](https://github.com/ishan0102/engblogs/issues/6) (already listed)
8. [Implement pagination](https://github.com/ishan0102/engblogs/issues/4) (already listed)
9. Add [search & filter](https://github.com/ishan0102/engblogs/issues/3) functionality. (already listed)

> P.S.: Regarding the "**4**" suggestion, I have a long list of technical blog links from various companies. I can provide them for you to update the feed sources by adding them to Supabase.

**Comment by ishan0102** [comment]
Thanks for the suggestions. 1/2 I probably won't do because I don't think I want this to be social so far, and don't want to implement accounts. Not sure what you had in mind for 3? Might do 4. For 5 feel free to comment any other RSS feeds I'm missing.

**Comment by Neilblaze** [comment]
@ishan0102 For *public vote*, it can be anonymous and is required if we want to display the (sorted) **daily highlights**. You can set a cron job to flush the db at the start of every month. For (**5**) here you go:

| Blog Link                                                                      | Description                                             |
| ------------------------------------------------------------------------------ | --------------------------------------------------------|
| [500px](https://developers.500px.com/)                                         | 500px Engineering Blog.                                 |                                         
| [8thLight](https://8thlight.com/blog/)                                         | 8th Light Engineering Blog.                             |
| [99Designs](https://99designs.com/tech-blog/)                                  | 99Designs Tech Blog.                                    |
| [9GAG](https://engineering.9gag.com/)                                          | 9GAG Engineering Blog.                                  |
| [Addepar](https://medium.com/build-addepar)                                    | Addepar Engineering Blog.                               |
| [Advanced Web Machinery](https://advancedweb.hu/)                              | Advanced web Machinery Blog.                            |
| [AdRoll](http://tech.adroll.com/blog/)                                         | AdRoll Engineering Blog.                                |
| [Affinity](https://build.affinity.co/)                                         | Affinity Engineering Blog.                              |
| [Affirm](https://tech.affirm.com/)                                             | Affirm Engineering Blog.                                |
| [AirBnB](http://nerds.airbnb.com/)                                             | AirBnB Engineering blog.                                |
| [AirBrake](https://airbrake.io/blog/)                                          | AirBrake Blog.                                          |                                         |
| [AirPair](https://www.airpair.com/software-experts)                            | AirPair Blog.                                           |
| [Airtame](https://airtame.engineering/)                                        | Airtame Blog.                                           |
| [Algolia](https://blog.algolia.com/)                                           | Algolia Blog.                                           |
| [Allegro](https://allegro.tech/)                                               | Allegro.tech Blog.                                      |
| [Amazon](https://developer.amazon.com/blogs)                                   | Amazon Developer Blog.                                  |
| [Artsy](https://artsy.github.io/)                                              | Artsy Engineering Blog.                                 |
| [Asana](https://blog.asana.com/category/eng/)                                  | Asana Engineering.                                      |
| [ASOS](https://medium.com/asos-techblog)                                       | ASOS Tech Blog.                                         |
| [Atlassian](https://developer.atlassian.com/blog/)                             | Atlassian Engineering Blog.                             |
| [Autodesk](http://cloudengineering.autodesk.com/blog/)                         | Autodesk Engineering Blog.                              |
| [AuthO](https://auth0.com/blog/)                                               | AuthO Engineering Blog.                                 |
| [Avant](http://avant.engineering/)                                             | Avant Engineering.                                      |
| [Babbel](https://bytes.babbel.com/en/)                                         | Babbel Engineering.                                     |
| [Backtrace](https://backtrace.io/blog/)                                        | Backtrace Blog.                                         |
| [Baidu Research](http://research.baidu.com/Blog)                               | Baidu Research Blog.                                    |
| [BandCamp](https://bandcamptech.wordpress.com/)                                | Bandcamp Tech.                                          |
| [BankSimple](https://www.simple.com/engineering)                               | Simple Blog.                                            |
| [BBC](https://medium.com/bbc-design-engineering/)                              | BBC Design & Engineering Blog.                          |
| [BenefitFocus](https://www.benefitfocus.com/blogs/design-engineering)          | Benefitfocus Engineering Blog.                          |
| [Better](https://better.engineering/)                                          | Better Engineering Blog.                                |
| [BetterWorks](https://engineering.betterworks.com/)                            | Betterworks Blog.                                       |
| [Bitly](http://word.bitly.com/)                                                | Bitly Engineering.                                      |
| [BitTorrent](http://engineering.bittorrent.com/)                               | BitTorrent Engineering Blog.                            |
| [Blablacar](http://blablatech.com/)                                            | Blablacar Engineering Blog.                             |
| [Blacklane](https://medium.com/blacklane-engineering)                          | Blacklane Engineering Blog.                             |
| [BlackRock Engineering](http://rockthecode.io/)                                | BlackRock Engineering Blog.                             |
| [Blend](https://blend.com/blog/engineering/)                                   | Blend Engineering Blog.                                 |
| [Blendle](https://blendle.engineering/)                                        | Blendle Engineering Blog.                               |
| [Bloomberg](https://www.techatbloomberg.com/blog/#2)                           | Tech At Bloomberg.                                      |
| [Branch](https://blog.branch.io/)                                              | Branch Blog.                                            |
| [Booking](https://blog.booking.com/)                                           | Booking.com Blog.                                       |
| [BookMyShow](https://we-are.bookmyshow.com/)                                   | BookMyShow Blog.                                        |
| [Canva](https://engineering.canva.com/)                                        | Canva Blog                                              |
| [Captricity](https://captricity.com/blog/)                                     | Captricity Blog.                                        |
| [Carbon Five](http://blog.carbonfive.com/)                                     | Carbon Five Blog.                                       |
| [Cerner](http://engineering.cerner.com/)                                       | Engineering Health, A Cerner Blog.                      |
| [C.H. Robinson](http://engineering.chrobinson.com/)                            | C.H. Robinson Engineering Blog, 3PL                     |
| [Chartbeat](http://engineering.chartbeat.com/)                                 | Chartbeat Engineering Blog.                             |
| [Cleartrip](https://medium.com/cleartrip)                                      | Cleartrip Blog.                                         |
| [Close.io](https://hack.close.io/)                                             | Close.io Engineering blog.                              |
| [Cloudera](https://blog.cloudera.com/)                                         | Cloudera Technical Blog.                                |
| [Cloudflare](https://blog.cloudflare.com/)                                     | Cloudflare blog.                                        |
| [Cloudscaling](https://cloudscaling.com/blog/)                                 | Cloudscaling Blog.                                      |
| [Codeminer42](https://blog.codeminer42.com/)                                   | The Miners, Codeminer42 Engineering Blog.               |
| [Compass](https://medium.com/compass-true-north/)                              | Compass Engineering Blog.                               |
| [Contentful](https://www.contentful.com/blog/)                                 | Contentful Blog.                                        |
| [Confluent](https://www.confluent.io/blog)                                     | Confluent Blog.                                         |
| [cookpad](https://sourcediving.com/)                                           | cookpad Blog.                                           |
| [Coursera](https://blog.coursera.org/)                                         | Coursera Blog.                                          |
| [ClusterHQ](https://clusterhq.com/blog/)                                       | ClusterHQ Blog.                                         |
| [Crowdbooster](http://blog.crowdbooster.com/)                                  | Crowdbooster Blog.                                      |
| [Dailymotion](http://engineering.dailymotion.com/)                             | Dailymotion Engineering Blog.                           |
| [Datadog](https://www.datadoghq.com/blog/engineering/)                         | Datadog Engineering Blog                                |
| [Datafloq](https://datafloq.com/read/)                                         | Datafloq Blog.                                          |
| [Dataiku](https://www.dataiku.com/blog/)                                       | Dataiku Blog.                                           |
| [DCHQ.io](http://dchq.co/blog.html)                                            | DCHQ Blog.                                              |
| [Making Dia](https://making.dia.com/)                                          | Dia&Co. Engineering Blog.                               |
| [Docker Blog](https://blog.docker.com/)                                        | Docker Blog.                                            |
| [Docker Engineering Blog](https://engineering.docker.com/)                     | Docker Engineering Blog.                                |
| [Docler Engineering Blog](https://medium.com/docler-engineering)               | Docler Engineering Blog.                                |
| [DoorDash Engineering Blog](https://doordash.engineering)                      | DoorDash Engineering Blog.                              |
| [Doximity](https://engineering.doximity.com)                                   | Doximity Engineering Blog.                              |
| [Dropbox](https://blogs.dropbox.com/tech/)                                     | Dropbox Tech Blog.                                      |
| [ebay](http://www.ebaytechblog.com)                                            | eBay Tech Blog.                                         |
| [Elastic](https://www.elastic.co/blog)                                         | Elastic Blog.                                           |
| [EngineYard](https://blog.engineyard.com/)                                     | Engine Yard Blog.                                       |
| [Etsy](https://codeascraft.com/)                                               | Code As Craft, Etsy Engineering Blog.                   |
| [Eventbrite](https://www.eventbrite.com/engineering/)                          | Eventbrite Engineering Blog.                            |
| [Evernote](https://blog.evernote.com/tech/)                                    | Evernote Tech Blog | The Care and Feeding of Elephants. |
| [Facebook](https://code.facebook.com/posts/)                                   | Facebook Engineering Blog.                              |
| [FastMail](https://blog.fastmail.com/)                                         | FastMail Blog.                                          |
| [Feedly](https://blog.feedly.com/)                                             | Feedly Blog.                                            |
| [FiftyThree](http://making.fiftythree.com/)                                    | Making Fifty Three.                                     |
| [Flickr](https://code.flickr.net/)                                             | Code.flickr.com.                                        |
| [Flipboard](http://engineering.flipboard.com/)                                 | Flipboard Engineering.                                  |
| [Flipkart](https://tech.flipkart.com/)                                    	 | Flipkart Engineering.                                   |
| [Fluidinfo](http://blogs.fluidinfo.com/)                                       | Fluidinfo Blog.                                         |
| [FourSquare](https://engineering.foursquare.com/)                              | Foursquare Engineering Blog.                            |
| [Freshworks Inc.](https://medium.com/freshworks-engineering-blog)              | The Freshworks Engineering Blog – Medium                |
| [GitHub](https://githubengineering.com/)                                       | The GitHub Blog: Engineering.                           |
| [Gnip](https://engineering.gnip.com/)                                          | Gnip Engineering.                                       |
| [Gojek](https://www.gojek.io/blog/tag/tech)                                    | Gojek Engineering.                                      |
| [Google Developers](https://developers.googleblog.com/)                        | Google Developers Blog.                                 |
| [Google AI Blog](https://ai.googleblog.com/)                                   | Google AI Blog.                                         |
| [GoSquared](https://engineering.gosquared.com/)                                | GoSquared Engineering Blog.                             |
| [Grab](http://engineering.grab.com/)                                           | Grab Tech Blog.                                         |
| [Grofers](https://lambda.grofers.com)                                          | Lambda-The Grofers Engineering Blog.                    |
| [Grouper](http://eng.joingrouper.com/)                                         | Grouper Engineering Team Blog.                          |
| [Groupon](https://engineering.groupon.com/)                                    | Groupon Engineering Blog.                               |
| [Gusto](http://engineering.gusto.com)                                          | Gusto Engineering Blog.                                 |
| [Globo.com](https://blog.globo.com/)                                           | Globo.com Engineering Blog.                                 |
| [Harry's](http://engineering.harrys.com/)                                      | Harry's Engineering.                                    |
| [Helpshift](https://medium.com/helpshift-engineering/)                         | Helpshift Engineering Blog.                             |
| [Heroku](https://engineering.heroku.com/)                                      | Heroku Engineering Blog.                                |
| [HoneyBadger](https://blog.honeybadger.io)                                     | HoneyBadger Blog.                                       |
| [Housing](https://medium.com/engineering-housing)                              | Housing Engineering Blog.                               |
| [HubbleHQ](https://hubblehq.com/blog)                                          | HubbleHQ Blog.                                          |
| [Hulu](https://tech.hulu.com/)                                                 | Hulu Tech Blog.                                         |
| [Icehouse](https://www.icehousecorp.com/blog/)                                 | Ice House Blog.                                         |
| [Import.io](https://www.import.io/blog/)                                       | Import.io Blog.                                         |
| [Indeed](http://engineering.indeedblog.com/blog/)                              | Indeed Engineering.                                     |
| [Influxdata](https://influxdata.com/blog/)                                     | Influxdata Blog.                                        |
| [Informed K12](https://tostring.informedk12.com/)                              | Informed K12 Engineering Blog.                          |
| [Instacart](https://tech.instacart.com/)                                       | Instacart Tech Blog.                                    |
| [Instagram](http://instagram-engineering.tumblr.com/)                          | Instagram Engineering.                                  |
| [IntentHQ](http://engineering.intenthq.com/)                                   | IntentHQ Engineering.                                   |
| [Intercom.io](https://blog.intercom.io)                                        | Intercom Blog.                                          |
| [iyzico](https://iyzico.engineering/)                                          | iyzico Engineering Blog.                                |
| [Jampp](https://geeks.jampp.com/)                                              | Jampp's Engineering Blog.                               |
| [Jelastic](https://blog.jelastic.com/)                                         | Jelastic Blog.                                          |
| [Jimdo](https://dev.jimdo.com/)                                                | Jimdo Dev Blog.                                         |
| [Jolly Good Code](https://jollygoodcode.github.io/)                            | Jolly Good Code Blog.                                   |
| [Kaggle](http://blog.kaggle.com/)                                              | Kaggle Blog.                                            |
| [Khan Academy Engineering Blog](http://engineering.khanacademy.org/)           | Khan Academy Engineering Blog.                          |
| [Levvel](https://www.levvel.io/blog/)                                          | Levvel Blog.                                            |
| [LinkedIn](https://engineering.linkedin.com/blog)                              | LinkedIn Engineering.                                   |
| [LiveChat](https://developers.livechatinc.com/blog/)                           | LiveChat Developers Blog.                               |
| [LoginRadius](https://www.loginradius.com/engineering/)                        | LoginRadius Engineering Blog.                           |
| [Lyft](https://eng.lyft.com/)                                                  | Lyft Engineering Blog.                                  |
| [Machinalis](https://www.machinalis.com/blog/)                                 | Machinalis Blog.                                        |
| [Mandrill](http://blog.mandrill.com/)                                          | Mandrill Blog.                                          |
| [Medallia](https://engineering.medallia.com/blog/)                             | Medallia Engineering Blog.                              |
| [Medium](https://medium.engineering/)                                          | Medium Engineering Blog.                                |
| [Mercari](https://engineering.mercari.com/en/blog/)                            | Mercari Engineering Blog.                               |
| [Microsoft](https://devblogs.microsoft.com/)                                   | Microsoft Developer Blogs.                              |
| [Mixmax](https://mixmax.com/eng/)                                              | Mixmax Engineering Blog.                                |
| [Mixpanel](https://mixpanel.com/blog/)                                         | Mixpanel Blog.                                          |
| [MojoAuth](https://mojoauth.com/blog/)                                         | MojoAuth Blog.                                          |
| [Monetate](http://engineering.monetate.com/)                                   | Monetate Engineering Blog.                              |
| [Mongodb](https://engineering.mongodb.com/)                                    | Mongodb Engineering Blog.                               |
| [Monsanto](http://engineering.monsanto.com/)                                   | Monsanto Engineering Blog.                              |
| [Mozilla](https://blog.mozilla.org/)                                           | The Mozilla Blog.                                       |
| [Myntra](https://medium.com/myntra-engineering)                                | Myntra Engineering Blog.                                |
| [Netflix](http://techblog.netflix.com/)                                        | Netflix Tech Blog.                                      |
| [Notion](https://www.notion.so/blog/topic/tech)                                | Notion Tech Blog.                                       |
| [Oyster](http://tech.oyster.com/)                                              | Insights from Oyster.com's Tech Team.                   |
| [Pagerduty](https://www.pagerduty.com/blog/)                                   | Pagerduty Blog.                                         |
| [Pagico](https://www.pagico.com/blog/)                                         | Pagico Blog.                                            |
| [PayPal](https://www.paypal-engineering.com/)                                  | PayPal Engineering.                                     |
| [Peapod](https://medium.com/peapod-engineering)                                | Peapod Propulsion Lab.                                  |
| [Persiscope Data](https://www.periscopedata.com/blog)                          | Periscope Data Blog.                                    |
| [Phyramid](https://www.phyramid.com/blog/)                                     | Phyramid Blog.                                          |
| [Pinterest](https://engineering.pinterest.com/)                                | Making Pinterest.                                       |
| [Postmarkapp](https://postmarkapp.com/blog)                                    | Postmarkapp Blog.                                       |
| [Practo](https://medium.com/practo-engineering)                                | Practo Engineering Blog.                                |
| [Prezi](https://engineering.prezi.com/)                                        | Prezi Engineering.                                      |
| [Quora](https://engineering.quora.com/)                                        | Engineering at Quora.                                   |
| [Raintank](https://blog.raintank.io/)                                          | Raintank Blog.                                          |
| [Ramp](https://engineering.ramp.com/)                                          | Ramp Engineering Blog.                                  |
| [Algorithm & Blues](https://algorithms.rdio.com/)                              | Rdio Engineering blog.                                  |
| [REA Group](http://techblog.realestate.com.au/engineering/)                    | REA Group Engineering Blog                              |
| [Reddit](https://redditblog.com/)                                              | What's New on Reddit.                                   |
| [Red Hat](https://developers.redhat.com/)                                      | Red Hat Developers Blog.                                |
| [Redfin](https://redfin.engineering/)                                          | Redfin Engineering Blog.                                | 
| [Rightscale](http://eng.rightscale.com/)                                       | Rightscale Engineering Blog.                            |
| [Riot Games Engineering](https://engineering.riotgames.com/)                   | Riot Games Engineering Blog.                            |
| [Robinhood](https://robinhood.engineering/)                                    | Robinhood Engineering Blog.                             |
| [Salesforce](https://engineering.salesforce.com/)                              | Salesforce Engineering Blog.                            |
| [Sensible](https://blog.sensible.io/)                                          | Sensible Blog.                                          |
| [Shopify](https://engineering.shopify.com)                                     | Shopify Engineering Blog.                               |
| [Showmax](https://tech.showmax.com)                                            | Showmax Engineering Blog.                               |
| [Simulmedia](http://www.simulmedia.com/resources/blog/categories/engineering/) | Simulmedia Engineering.                                 |
| [Slack](https://slack.engineering/)                                            | Slack Engineering Blog.                                 |
| [SlideShare](http://engineering.slideshare.net/)                               | SlideShare Engineering Blog.                            |
| [SmugMug](http://engineering.slideshare.com/)                                  | SmugMug's Don MacAskill.                                |
| [Snap](https://eng.snap.com/blog/)                                             | Snap's (Snapchat) Engineering Blog                      |
| [Snapdeal](http://engineering.snapdeal.com/)                                   | Snapdeal Engineering Blog.                              |
| [Songkick](https://devblog.songkick.com/)                                      | Songkick Technology Blog.                               |
| [SoundCloud](https://developers.soundcloud.com/blog/)                          | SoundCloud Backstage.                                   |
| [Spotify](https://labs.spotify.com/)                                           | Spotify's Engineering and Technology Blog.              |
| [Squadcast](https://www.squadcast.com/blog)                                    | Squadcast's site reliability engineering blog.          |
| [Square](https://developer.squareup.com/blog/)                                 | The Corner, Square Engineering Blog.                    |
| [Strava](http://labs.strava.com)                                               | Strava Labs.                                            |
| [Stitch Fix](http://multithreaded.stitchfix.com/blog/)                         | Stitch Fix Engineering Blog.                            |
| [StormPath](https://stormpath.com/blog/)                                       | StormPath Blog.                                         |
| [Stripe](https://stripe.com/blog/engineering)                                  | Stripe Engineering Blog.                                |
| [Stylight](https://tech.stylight.com/)                                         | Stylight Tech Blog                                      |
| [Swiggy](https://bytes.swiggy.com/)                                            | Swiggy Engineering                                      |
| [TellApart](https://www.tellapart.com/engineering-blog/)                       | TellApart Blog.                                         |
| [ThoughtWorks](https://www.thoughtworks.com/insights)                          | ThoughtWorks Engineering Blog.                          |
| [Toptal](https://www.toptal.com/blog)                                          | Toptal Blog.                                            |
| [Tumblr](https://engineering.tumblr.com/)                                      | Tumblr Engineering.                                     |
| [Twitter](https://blog.twitter.com/engineering)                                | Twitter Engineering.                                    |
| [Twilio](https://www.twilio.com/engineering/)                                  | Twilio Engineering.                                     |
| [Thumbtack](https://www.thumbtack.com/engineering/)                            | Thumbtack Engineering.                                  |
| [TwoSigma](https://www.twosigma.com/insights/category/technology)              | TwoSigma Technology Blog.                               |
| [Uber](https://eng.uber.com/)                                                  | Uber Engineering.                                       |
| [Udacity](https://blog.udacity.com/)                                           | Udacity Blog.                                           |
| [Venmo](http://blog.venmo.com/?category=Engineering)                           | Venmo Blog.                                             |
| [Walmart Labs](https://medium.com/walmartlabs)                                 | Walmart Labs Engineering Blog.                          |
| [Wayfair](https://engineering.wayfair.com/)                                    | Wayfair Engineering.                                    |
| [Wealthfront](https://eng.wealthfront.com/)                                    | Wealthfront Engineering.                                |
| [WebEngage](https://engineering.webengage.com/)                                | WebEngage Engineering Blog.                             |
| [Wix](https://www.wix.engineering/blog)                                        | Wix Engineering Blog.                                   |
| [Workshape](http://blog.workshape.io/)                                         | Workshape Blog.                                         |
| [Yahoo!](https://yahooeng.tumblr.com/)                                         | Yahoo! Engineering Blog.                                |
| [Yammer](https://medium.com/@YammerEng)                                        | Blog Yammer Engineering.                                |
| [Yelp](https://engineeringblog.yelp.com/)                                      | Yelp Product and Engineering Blog.                      |
| [YouTube](https://youtube-eng.googleblog.com/)                                 | YouTube Engineering and Developers Blog.                |
| [Zalando](https://tech.zalando.com/blog/)                                      | Zalando Tech Blog.                                      |
| [Zapier](https://zapier.com/engineering/)                                      | Zapier Engineering Blog.                                |
| [Zenefits](https://engineering.zenefits.com/posts/)                            | Zenefits Engineering Blog.                              |
| [Zerodha](https://zerodha.tech/blog/)                                          | Zerodha Tech Blog.                                      |
| [Zillow](https://www.zillow.com/engineering/)                                  | Zillow Engineering Blog.                                |
| [Zomato](https://engineering.zomato.com/)                                      | Zomato Engineering Blog.                                |
| [Zynga](https://www.zynga.com/blogs/engineering)                               | Zynga Engineering Blog.                                 |

**Comment by ishan0102** [comment]
Thanks for the blog links, super useful. Just added 30 new companies into the mix.

**Comment by Neilblaze** [comment]
@ishan0102 You're welcome! Lemme know if you need anything else :)
